version: '3.8'

services:

    nginx:
        container_name: nginx
        image: nginx:latest
        ports: 
            - 80:80
        volumes: 
            - ./app/:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - app
        
    app:
        container_name: app
        build: ./php/
        volumes:
            - ./app/:/var/www/html
        env_file: .env
        environment: 
            DATABASE_HOST: db
        depends_on: 
            - db

    db:
        container_name: mysql
        image: mysql:5.7
        ports: 
            - 3306:3306
        volumes: 
            - ./db-data/:/var/lib/mysql
        env_file: .env